services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Command\CleanupCommand:
        arguments:
            $linkLifetime: '%env(LINK_LIFETIME)%'

    App\Controller\RedirectController:
        arguments:
            $linkTemplate: '%env(LINK_TEMPLATE)%'
            $linkHost: '%env(LINK_HOST)%'